name: integration tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    container: golang:1.18.2-bullseye
    steps:
      - uses: actions/checkout@v2
      - name: Download modules
        run: go mod tidy
      - name: Integration Tests
        run: go test -v -race ./...
        working-directory: tests/integration
        env:
          RHS_URL: http://rhs:8080
    services:
      rhs:
        image: ghcr.io/iden3/reverse-hash-service:latest
        credentials:
          username: ${{ secrets.RHS_DOCKER_LOGIN }}
          password: ${{ secrets.RHS_DOCKER_PASSWORD }}
        env:
          RHS_DB: "host=postgres password=pgpwd user=postgres"
        volumes:
          - vrhs:/opt
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_PASSWORD: pgpwd
        volumes:
          - vrhs:/docker-entrypoint-initdb.d
