name: integration tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers: [ 1.18.0-bullseye ]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containers }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Unit Tests
        run: go test -v -race ./...
        working-directory: tests/integration
        env:
          RHS_URL: http://rhs:8080
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_PASSWORD: pgpwd
        volumes:
          - vrhs:/docker-entrypoint-initdb.d
      rhs:
        image: ghcr.io/iden3/reverse-hash-service:latest
        env:
          RHS_DB: "host=postgres password=pgpwd user=postgres"
        volumes:
          - vrhs:/opt
